# Generated by Django 5.2.11 on 2026-02-26 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('planned_to', 'Planned Technical Inspection'), ('current_repair', 'Current Repair'), ('major_repair', 'Major Repair')], max_length=20)),
                ('opened_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('fault_description', models.TextField()),
                ('work_performed', models.TextField(blank=True)),
                ('contractor_name', models.CharField(blank=True, max_length=255)),
                ('parts_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('odometer_at_closing', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Maintenance Record',
                'verbose_name_plural': 'Maintenance Records',
                'db_table': 'maintenance_records',
                'ordering': ['-opened_at'],
                'indexes': [models.Index(fields=['vehicle', 'opened_at'], name='idx_maint_vehicle_date'), models.Index(fields=['closed_at'], name='idx_maint_closed_at')],
                'constraints': [models.CheckConstraint(condition=models.Q(('parts_cost__gte', 0)), name='chk_maint_non_negative_parts'), models.CheckConstraint(condition=models.Q(('labor_cost__gte', 0)), name='chk_maint_non_negative_labor')],
            },
        ),
    ]
