# Generated by Django 5.2.11 on 2026-02-26 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fueled_at', models.DateTimeField()),
                ('fuel_liters', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_liter', models.DecimalField(decimal_places=2, max_digits=10)),
                ('station_name', models.CharField(max_length=255)),
                ('odometer_at_fueling', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actual_consumption', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('deviation_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('is_anomalous', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fueling_records', to='drivers.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fueling_records', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Fueling Record',
                'verbose_name_plural': 'Fueling Records',
                'db_table': 'fueling_records',
                'ordering': ['-fueled_at'],
                'indexes': [models.Index(fields=['vehicle', 'fueled_at'], name='idx_fueling_vehicle_date'), models.Index(fields=['driver', 'fueled_at'], name='idx_fueling_driver_date'), models.Index(fields=['is_anomalous'], name='idx_fueling_anomalous')],
                'constraints': [models.CheckConstraint(condition=models.Q(('fuel_liters__gt', 0)), name='chk_fueling_positive_liters'), models.CheckConstraint(condition=models.Q(('price_per_liter__gt', 0)), name='chk_fueling_positive_price'), models.CheckConstraint(condition=models.Q(('odometer_at_fueling__gte', 0)), name='chk_fueling_non_negative_odometer')],
            },
        ),
    ]
